# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\kelbera\Documents\DEV\PYTHON\pyQArk_base\pyQArk\Dialogs\QArkWorkerThreadRunExtendedDialog\QArkWorkerThreadRunExtendedDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QArkWorkerThreadRunExtendedDialog(object):
    def setupUi(self, QArkWorkerThreadRunExtendedDialog):
        QArkWorkerThreadRunExtendedDialog.setObjectName("QArkWorkerThreadRunExtendedDialog")
        QArkWorkerThreadRunExtendedDialog.setWindowModality(QtCore.Qt.WindowModal)
        QArkWorkerThreadRunExtendedDialog.resize(477, 334)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QArkWorkerThreadRunExtendedDialog.sizePolicy().hasHeightForWidth())
        QArkWorkerThreadRunExtendedDialog.setSizePolicy(sizePolicy)
        QArkWorkerThreadRunExtendedDialog.setModal(True)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(QArkWorkerThreadRunExtendedDialog)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame = QtWidgets.QFrame(QArkWorkerThreadRunExtendedDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.movieLabel = QtWidgets.QLabel(self.frame)
        self.movieLabel.setText("")
        self.movieLabel.setObjectName("movieLabel")
        self.gridLayout.addWidget(self.movieLabel, 0, 0, 3, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.promptLabel = QtWidgets.QLabel(self.frame)
        self.promptLabel.setObjectName("promptLabel")
        self.gridLayout.addWidget(self.promptLabel, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 2, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.keepOpenCheckBox = QtWidgets.QCheckBox(self.frame)
        self.keepOpenCheckBox.setChecked(True)
        self.keepOpenCheckBox.setObjectName("keepOpenCheckBox")
        self.horizontalLayout.addWidget(self.keepOpenCheckBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.showDetailsPushButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showDetailsPushButton.sizePolicy().hasHeightForWidth())
        self.showDetailsPushButton.setSizePolicy(sizePolicy)
        self.showDetailsPushButton.setObjectName("showDetailsPushButton")
        self.horizontalLayout.addWidget(self.showDetailsPushButton)
        spacerItem4 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Abort|QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addWidget(self.frame)
        self.tabWidget = QtWidgets.QTabWidget(QArkWorkerThreadRunExtendedDialog)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setObjectName("tabWidget")
        self.stdoutTab = QtWidgets.QWidget()
        self.stdoutTab.setObjectName("stdoutTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.stdoutTab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stdoutPlainTextEdit = QtWidgets.QPlainTextEdit(self.stdoutTab)
        self.stdoutPlainTextEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stdoutPlainTextEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.stdoutPlainTextEdit.setReadOnly(True)
        self.stdoutPlainTextEdit.setObjectName("stdoutPlainTextEdit")
        self.verticalLayout.addWidget(self.stdoutPlainTextEdit)
        self.tabWidget.addTab(self.stdoutTab, "")
        self.stderrTab = QtWidgets.QWidget()
        self.stderrTab.setObjectName("stderrTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.stderrTab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stderrPlainTextEdit = QtWidgets.QPlainTextEdit(self.stderrTab)
        self.stderrPlainTextEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.stderrPlainTextEdit.setObjectName("stderrPlainTextEdit")
        self.verticalLayout_2.addWidget(self.stderrPlainTextEdit)
        self.tabWidget.addTab(self.stderrTab, "")
        self.verticalLayout_5.addWidget(self.tabWidget)

        self.retranslateUi(QArkWorkerThreadRunExtendedDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(QArkWorkerThreadRunExtendedDialog.accept)
        self.buttonBox.rejected.connect(QArkWorkerThreadRunExtendedDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(QArkWorkerThreadRunExtendedDialog)

    def retranslateUi(self, QArkWorkerThreadRunExtendedDialog):
        _translate = QtCore.QCoreApplication.translate
        QArkWorkerThreadRunExtendedDialog.setWindowTitle(_translate("QArkWorkerThreadRunExtendedDialog", "Dialog"))
        self.promptLabel.setText(_translate("QArkWorkerThreadRunExtendedDialog", "Please wait..."))
        self.keepOpenCheckBox.setText(_translate("QArkWorkerThreadRunExtendedDialog", "Keep dialog open"))
        self.showDetailsPushButton.setText(_translate("QArkWorkerThreadRunExtendedDialog", "Show details"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.stdoutTab), _translate("QArkWorkerThreadRunExtendedDialog", "StdOut"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.stderrTab), _translate("QArkWorkerThreadRunExtendedDialog", "StdErr"))

