# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QArkExportPlotWidgetDialog.ui'
#
# Created: Tue Sep 23 12:48:25 2014
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_QArkExportPlotWidgetDialog(object):
    def setupUi(self, QArkExportPlotWidgetDialog):
        QArkExportPlotWidgetDialog.setObjectName(_fromUtf8("QArkExportPlotWidgetDialog"))
        QArkExportPlotWidgetDialog.resize(406, 189)
        self.verticalLayout = QtGui.QVBoxLayout(QArkExportPlotWidgetDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.directoryLabel = QtGui.QLabel(QArkExportPlotWidgetDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directoryLabel.sizePolicy().hasHeightForWidth())
        self.directoryLabel.setSizePolicy(sizePolicy)
        self.directoryLabel.setObjectName(_fromUtf8("directoryLabel"))
        self.gridLayout.addWidget(self.directoryLabel, 0, 0, 1, 1)
        self.directoryLineEdit = QtGui.QLineEdit(QArkExportPlotWidgetDialog)
        self.directoryLineEdit.setObjectName(_fromUtf8("directoryLineEdit"))
        self.gridLayout.addWidget(self.directoryLineEdit, 0, 1, 1, 3)
        self.directoryToolButton = QtGui.QToolButton(QArkExportPlotWidgetDialog)
        self.directoryToolButton.setObjectName(_fromUtf8("directoryToolButton"))
        self.gridLayout.addWidget(self.directoryToolButton, 0, 4, 1, 1)
        self.fileLabel = QtGui.QLabel(QArkExportPlotWidgetDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileLabel.sizePolicy().hasHeightForWidth())
        self.fileLabel.setSizePolicy(sizePolicy)
        self.fileLabel.setObjectName(_fromUtf8("fileLabel"))
        self.gridLayout.addWidget(self.fileLabel, 1, 0, 1, 1)
        self.fileLineEdit = QtGui.QLineEdit(QArkExportPlotWidgetDialog)
        self.fileLineEdit.setObjectName(_fromUtf8("fileLineEdit"))
        self.gridLayout.addWidget(self.fileLineEdit, 1, 1, 1, 4)
        self.formatLabel = QtGui.QLabel(QArkExportPlotWidgetDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formatLabel.sizePolicy().hasHeightForWidth())
        self.formatLabel.setSizePolicy(sizePolicy)
        self.formatLabel.setObjectName(_fromUtf8("formatLabel"))
        self.gridLayout.addWidget(self.formatLabel, 2, 0, 1, 1)
        self.formatComboBox = QtGui.QComboBox(QArkExportPlotWidgetDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formatComboBox.sizePolicy().hasHeightForWidth())
        self.formatComboBox.setSizePolicy(sizePolicy)
        self.formatComboBox.setMinimumSize(QtCore.QSize(70, 0))
        self.formatComboBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.formatComboBox.setObjectName(_fromUtf8("formatComboBox"))
        self.gridLayout.addWidget(self.formatComboBox, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(258, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 3)
        self.widthLabel = QtGui.QLabel(QArkExportPlotWidgetDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthLabel.sizePolicy().hasHeightForWidth())
        self.widthLabel.setSizePolicy(sizePolicy)
        self.widthLabel.setObjectName(_fromUtf8("widthLabel"))
        self.gridLayout.addWidget(self.widthLabel, 3, 0, 1, 1)
        self.widthSpinBox = QtGui.QSpinBox(QArkExportPlotWidgetDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthSpinBox.sizePolicy().hasHeightForWidth())
        self.widthSpinBox.setSizePolicy(sizePolicy)
        self.widthSpinBox.setMinimumSize(QtCore.QSize(70, 0))
        self.widthSpinBox.setMaximumSize(QtCore.QSize(70, 16777215))
        self.widthSpinBox.setMinimum(128)
        self.widthSpinBox.setMaximum(2048)
        self.widthSpinBox.setSingleStep(16)
        self.widthSpinBox.setProperty("value", 512)
        self.widthSpinBox.setObjectName(_fromUtf8("widthSpinBox"))
        self.gridLayout.addWidget(self.widthSpinBox, 3, 1, 1, 1)
        self.widthMessageLabel = QtGui.QLabel(QArkExportPlotWidgetDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthMessageLabel.sizePolicy().hasHeightForWidth())
        self.widthMessageLabel.setSizePolicy(sizePolicy)
        self.widthMessageLabel.setObjectName(_fromUtf8("widthMessageLabel"))
        self.gridLayout.addWidget(self.widthMessageLabel, 3, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 3, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.buttonBox = QtGui.QDialogButtonBox(QArkExportPlotWidgetDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(QArkExportPlotWidgetDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), QArkExportPlotWidgetDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), QArkExportPlotWidgetDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(QArkExportPlotWidgetDialog)

    def retranslateUi(self, QArkExportPlotWidgetDialog):
        QArkExportPlotWidgetDialog.setWindowTitle(QtGui.QApplication.translate("QArkExportPlotWidgetDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.directoryLabel.setText(QtGui.QApplication.translate("QArkExportPlotWidgetDialog", "Répertoire", None, QtGui.QApplication.UnicodeUTF8))
        self.directoryToolButton.setText(QtGui.QApplication.translate("QArkExportPlotWidgetDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.fileLabel.setText(QtGui.QApplication.translate("QArkExportPlotWidgetDialog", "Fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.formatLabel.setText(QtGui.QApplication.translate("QArkExportPlotWidgetDialog", "Format", None, QtGui.QApplication.UnicodeUTF8))
        self.widthLabel.setText(QtGui.QApplication.translate("QArkExportPlotWidgetDialog", "Largeur", None, QtGui.QApplication.UnicodeUTF8))
        self.widthMessageLabel.setText(QtGui.QApplication.translate("QArkExportPlotWidgetDialog", "(adaptation automatique de la hauteur)", None, QtGui.QApplication.UnicodeUTF8))

