# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QArkPlotPenSettingsWidget.ui'
#
# Created: Mon Aug  4 08:52:01 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_QArkPlotPenSettingsWidget(object):
    def setupUi(self, QArkPlotPenSettingsWidget):
        QArkPlotPenSettingsWidget.setObjectName(_fromUtf8("QArkPlotPenSettingsWidget"))
        QArkPlotPenSettingsWidget.resize(276, 94)
        self.gridLayout_2 = QtGui.QGridLayout(QArkPlotPenSettingsWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox = QtGui.QGroupBox(QArkPlotPenSettingsWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setMargin(2)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.colorLabel = QArkClickableFilledRect(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorLabel.sizePolicy().hasHeightForWidth())
        self.colorLabel.setSizePolicy(sizePolicy)
        self.colorLabel.setFrameShape(QtGui.QFrame.Box)
        self.colorLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.colorLabel.setObjectName(_fromUtf8("colorLabel"))
        self.gridLayout.addWidget(self.colorLabel, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.redLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.redLabel.sizePolicy().hasHeightForWidth())
        self.redLabel.setSizePolicy(sizePolicy)
        self.redLabel.setObjectName(_fromUtf8("redLabel"))
        self.horizontalLayout.addWidget(self.redLabel)
        self.redSpinBox = QtGui.QSpinBox(self.groupBox)
        self.redSpinBox.setMaximum(255)
        self.redSpinBox.setObjectName(_fromUtf8("redSpinBox"))
        self.horizontalLayout.addWidget(self.redSpinBox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 0, 2, 3, 1)
        self.widthLabel = QtGui.QLabel(self.groupBox)
        self.widthLabel.setObjectName(_fromUtf8("widthLabel"))
        self.gridLayout.addWidget(self.widthLabel, 0, 3, 1, 1)
        self.widthSpinBox = QtGui.QSpinBox(self.groupBox)
        self.widthSpinBox.setObjectName(_fromUtf8("widthSpinBox"))
        self.gridLayout.addWidget(self.widthSpinBox, 0, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 45, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 2, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.greenLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.greenLabel.sizePolicy().hasHeightForWidth())
        self.greenLabel.setSizePolicy(sizePolicy)
        self.greenLabel.setObjectName(_fromUtf8("greenLabel"))
        self.horizontalLayout_2.addWidget(self.greenLabel)
        self.greenSpinBox = QtGui.QSpinBox(self.groupBox)
        self.greenSpinBox.setMaximum(255)
        self.greenSpinBox.setObjectName(_fromUtf8("greenSpinBox"))
        self.horizontalLayout_2.addWidget(self.greenSpinBox)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.styleLabel = QtGui.QLabel(self.groupBox)
        self.styleLabel.setObjectName(_fromUtf8("styleLabel"))
        self.gridLayout.addWidget(self.styleLabel, 1, 3, 1, 1)
        self.styleComboBox = QtGui.QComboBox(self.groupBox)
        self.styleComboBox.setObjectName(_fromUtf8("styleComboBox"))
        self.gridLayout.addWidget(self.styleComboBox, 1, 4, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.blueLabel = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blueLabel.sizePolicy().hasHeightForWidth())
        self.blueLabel.setSizePolicy(sizePolicy)
        self.blueLabel.setObjectName(_fromUtf8("blueLabel"))
        self.horizontalLayout_3.addWidget(self.blueLabel)
        self.blueSpinBox = QtGui.QSpinBox(self.groupBox)
        self.blueSpinBox.setMaximum(255)
        self.blueSpinBox.setObjectName(_fromUtf8("blueSpinBox"))
        self.horizontalLayout_3.addWidget(self.blueSpinBox)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(51, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 3, 1, 1)
        self.applyPushButton = QtGui.QPushButton(self.groupBox)
        self.applyPushButton.setObjectName(_fromUtf8("applyPushButton"))
        self.gridLayout.addWidget(self.applyPushButton, 2, 4, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(QArkPlotPenSettingsWidget)
        QtCore.QMetaObject.connectSlotsByName(QArkPlotPenSettingsWidget)

    def retranslateUi(self, QArkPlotPenSettingsWidget):
        QArkPlotPenSettingsWidget.setWindowTitle(QtGui.QApplication.translate("QArkPlotPenSettingsWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("QArkPlotPenSettingsWidget", "Couleur et style", None, QtGui.QApplication.UnicodeUTF8))
        self.colorLabel.setText(QtGui.QApplication.translate("QArkPlotPenSettingsWidget", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.redLabel.setText(QtGui.QApplication.translate("QArkPlotPenSettingsWidget", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.widthLabel.setText(QtGui.QApplication.translate("QArkPlotPenSettingsWidget", "Epaisseur", None, QtGui.QApplication.UnicodeUTF8))
        self.greenLabel.setText(QtGui.QApplication.translate("QArkPlotPenSettingsWidget", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.styleLabel.setText(QtGui.QApplication.translate("QArkPlotPenSettingsWidget", "Style", None, QtGui.QApplication.UnicodeUTF8))
        self.blueLabel.setText(QtGui.QApplication.translate("QArkPlotPenSettingsWidget", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.applyPushButton.setText(QtGui.QApplication.translate("QArkPlotPenSettingsWidget", "Appliquer", None, QtGui.QApplication.UnicodeUTF8))

from ..QArkClickableFilledRect.QArkClickableFilledRect import QArkClickableFilledRect
